sonar.projectKey=hirparaayushi-arch_8.2CDevSecOps
sonar.organization=hirparaayushi-arch
sonar.host.url=https://sonarcloud.io
sonar.login=4830707ece82a864448879bde68bac26d5af8637

sonar.sources=.
sonar.exclusions=node_modules/**,test/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.projectName=NodeJS Goof Vulnerable App
sonar.sourceEncoding=UTF-8